[project]
name = "unicorn-leaderboard"
version = "1.0.0"
description = "Unicorn Global Leaderboard Datasette Instance"
requires-python = ">=3.12"
dependencies = [
    "datasette>=0.65.0",
    "asyncpg",
    "psycopg2-binary",
]
